name: sync_tekton_gcr
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 2 * * 1-5"
jobs:
  build:
    name: build_and_push
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - name: Build golang
        run: go build
      - name: tag and push
        run: ./tekton-gcr-to-docker-hub > build_and_push.sh
      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3.2.0"
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWD }}"
        run: |-
          /bin/sh build_and_push.sh
      - name: new install yaml
        run: ./tekton-gcr-to-docker-hub > install-with-docker-reg.yaml
      - name: new release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          # GitHub secret token
          repo_token: ${{ secrets.GIT_REPO_RW }}
          # Git tag (for automatic releases)
          automatic_release_tag: ${{ env.ReleaseVersion }}
          prerelease: false
          files: |
            install-with-docker-reg.yaml
